# Generated by Django 5.1.4 on 2025-08-10 06:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('twilio_account_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('twilio_auth_token', models.CharField(blank=True, max_length=255, null=True)),
                ('vapi_api_key', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='api_config', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewAssistant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('vapi_assistant_id', models.CharField(max_length=255, unique=True)),
                ('first_message', models.TextField()),
                ('voice_provider', models.CharField(default='openai', max_length=50)),
                ('voice_id', models.CharField(default='nova', max_length=100)),
                ('model_provider', models.CharField(default='openai', max_length=50)),
                ('model', models.CharField(default='gpt-4', max_length=100)),
                ('knowledge_text', models.TextField(blank=True, null=True)),
                ('knowledge_urls', models.TextField(blank=True, null=True)),
                ('configuration', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PhoneNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=20)),
                ('vapi_phone_number_id', models.CharField(max_length=255, unique=True)),
                ('twilio_sid', models.CharField(blank=True, max_length=255, null=True)),
                ('friendly_name', models.CharField(blank=True, max_length=255, null=True)),
                ('capabilities', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewCall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vapi_call_id', models.CharField(max_length=255, unique=True)),
                ('customer_number', models.CharField(max_length=20)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('ringing', 'Ringing'), ('in-progress', 'In Progress'), ('ended', 'Ended'), ('failed', 'Failed')], default='queued', max_length=20)),
                ('outcome_status', models.CharField(blank=True, choices=[('answered', 'Answered'), ('answered-brief', 'Answered (Brief)'), ('voicemail', 'Voicemail'), ('no-answer', 'No Answer'), ('busy', 'Busy'), ('declined', 'Declined'), ('failed', 'Failed'), ('in-progress', 'In Progress'), ('ringing', 'Ringing'), ('completed', 'Completed'), ('unknown', 'Unknown')], max_length=20, null=True)),
                ('outcome_description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('transcript', models.JSONField(blank=True, default=list)),
                ('transcript_text', models.TextField(blank=True, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True)),
                ('cost_breakdown', models.JSONField(blank=True, default=dict)),
                ('duration_seconds', models.IntegerField(blank=True, null=True)),
                ('end_reason', models.CharField(blank=True, max_length=255, null=True)),
                ('raw_call_data', models.JSONField(blank=True, default=dict)),
                ('assistant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='api.interviewassistant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to=settings.AUTH_USER_MODEL)),
                ('phone_number', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='api.phonenumber')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
