# Generated by Django 5.1.4 on 2025-08-11 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_campaign'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewassistant',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assistants', to='api.campaign'),
        ),
        migrations.AddField(
            model_name='interviewcall',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='calls', to='api.campaign'),
        ),
        migrations.AddField(
            model_name='phonenumber',
            name='campaign',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='phone_numbers', to='api.campaign'),
        ),
    ]
