# Generated by Django 5.1.4 on 2025-08-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_scheduledcall'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledcall',
            name='timezone',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
