# Generated by Django 5.1.4 on 2025-08-15 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_scheduledcall_timezone'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewcall',
            name='processed_transcript',
            field=models.TextField(blank=True, null=True),
        ),
    ]
