# Generated by Django 5.1.4 on 2025-08-20 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_interviewcall_processed_transcript'),
    ]

    operations = [
        migrations.AddField(
            model_name='apiconfiguration',
            name='openai_api_key',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
