# Generated by Django 5.1.4 on 2025-08-20 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_apiconfiguration_openai_api_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewcall',
            name='recording_file',
            field=models.FileField(blank=True, null=True, upload_to='call_recordings/'),
        ),
        migrations.AddField(
            model_name='interviewcall',
            name='recording_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
