# Generated by Django 5.1.4 on 2025-08-22 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_interviewcall_recording_file_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phonenumber',
            name='assistant',
            field=models.ForeignKey(blank=True, help_text='Assistant that will answer inbound calls to this number', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_phone_numbers', to='api.interviewassistant'),
        ),
    ]
