# Generated by Django 5.1.4 on 2025-08-22 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_phonenumber_assistant'),
    ]

    operations = [
        migrations.AddField(
            model_name='interviewcall',
            name='call_type',
            field=models.CharField(choices=[('outbound', 'Outbound'), ('inbound', 'Inbound')], default='outbound', max_length=10),
        ),
    ]
